BEGIN TRANSACTION 
UPDATE NotaFiscal 
SET Tp_EntradaSaida=1
WHERE CD_NF = 4040;
COMMIT TRANSACTION;

SELECT * FROM NotaFiscal 

BEGIN TRANSACTION 
UPDATE NotaFiscal 
SET Tp_EntradaSaida=0
WHERE CD_NF = 4040;
ROLLBACK;

SELECT * FROM NotaFiscal 
